### ISSUE TITLE
No response from the server

### ISSUE THREAD

**Issue by aminfallahi** [hcoz/sem-cli#3]
I am trying "sem-look list files" and it is calling http://sem-cli-serverless.azurewebsites.net/api/inquire?q=list%20files&os=linux but there is no response from the API. Is there anything I need to do to make it work?

**Comment by hcoz** [comment]
Hi,
Unfortunately, all commands are for macOS & Windows currently. For example, if you try the followings, you will get a response:
http://sem-cli-serverless.azurewebsites.net/api/inquire?q=list%20files&os=darwin
http://sem-cli-serverless.azurewebsites.net/api/inquire?q=list%20files&os=win32

Actually, improvement of the database is the main struggle in this project and that's why I added `sem-suggest` command. It enables the collaborated enhancement of data.
Btw, I added list files for Linux. So your request will have a response now :)
